### ISSUE TITLE
Do not work for windows.

### ISSUE THREAD

**Issue by dzwdyc** [Xrysnow/cocos2d-x-imgui#2]
Hi, Dose it support for  windows platform?
thanks!

**Comment by Xrysnow** [comment]
Yes, actually it is designed to support all platforms. You can put some more information if you meet a bug.

**Comment by kacmazemin** [comment]
hey, is that library support for multiple window? I would like to use in my cocos2dx project.

**Comment by Xrysnow** [comment]
@kacmazemin If you mean the Multi-Viewport, the answer is yes. All features of imgui are available on desktop platforms.

**Comment by kacmazemin** [comment]
I have tried in mac. Just added
```
#ifdef CC_PLATFORM_MAC
    io.BackendFlags |= ImGuiConfigFlags_DockingEnable;
    io.BackendFlags |= ImGuiConfigFlags_ViewportsEnable;
#endif
``` 
to imgui_impl_cocos2dx.cpp , of course I updated files from https://github.com/ocornut/imgui docking branch. But nothing changed

**Comment by Xrysnow** [comment]
@kacmazemin Some implements are missing. I will try to fix it.

**Comment by kacmazemin** [comment]
<img width="329" alt="Screen Shot 2020-06-21 at 17 44 39" src="https://user-images.githubusercontent.com/24880963/85227568-f60b3100-b3e6-11ea-8cb7-61aa94f32acb.png">

@Xrysnow  I tried via demo. when I click turn checkbox of viewports enable on, its gone directly

**Comment by Xrysnow** [comment]
@kacmazemin I have updated codes and implemented viewports. But I'm not sure if it works on mac because I only tested on windows.

**Comment by halx99** [comment]
@Xrysnow hello, I have test on mac, multi-viewports seems doesn't work, see
https://github.com/ocornut/imgui/issues/551
